Fmpz mat mul blas tuning
wbhart/flint2 pull request #909
Opened 2021-03-24 14:17 UTC by wbhart

This:

* Switches to 20 bit primes in fmpz_mat_mul_modular when BLAS is available
* Adds fmpz_mat_mul_blas to tuning code and tunes over a more reasonable range of sizes
* Redoes the tuning for fmpz_mat_mul for the new fmpz_mat_mul_blas of @tthsqe12 when BLAS is available
* Uses strassen more when there is 1 thread

This is expected to fail until #903 is merged.

2021-03-24 19:23 UTC, tthsqe12 commented
This is a clear regression on 500x500x4000bit matrices. Needs more work.

2021-03-24 19:28 UTC, wbhart commented
It's easy to find points where this is a regression. It's a multivariate problem and impossible to do without some points being off.

2021-03-24 19:33 UTC, wbhart commented
Feel free to add additional conditions, but please do the benchmarking on a modern system. I used a system with 8 cores that is less than a year old.

2021-03-24 20:22 UTC, fredrik-johansson commented
Is the new condition

        ((abits + bbits >= 20  && abits + bbits < 60 && dim > 150) || (dim > 500)))
            fmpz_mat_mul_strassen(C, A, B);

*without*  FLINT_USES_BLAS deliberate? It would look a bit cleaner if we keep the BLAS-specific conditions together in one if-block instead of having three #if FLINT_USES_BLAS sections.

2021-03-24 21:27 UTC, wbhart commented
It was deliberate. By all means suggest something better. I was simply trying to not have pages of ifs.

2021-03-25 08:58 UTC, tthsqe12 commented
Here are my reasons for not understanding this pr:
- the base cases of strassen are not currently optimized and threaded
- mul_multi_modular is not optimized and threaded
- since there are clear regressions, if we merge this and then optimize and (try to) thread said functions, the new tuning is going to have to be against master minus (parts) of this pr.

2021-03-25 09:37 UTC, wbhart commented
As I explained, the only base case in strassen is 4x4 classical multiplication. It's never called for such low dimensions, so instead it calls fmpz_mat_mul to decide what to call after one layer of Strassen. If fmpz_mat_mul is threaded at that point then the base cases of Strassen will in fact be threaded.

If the dimension is large, mul_multi_modular will (presumably) have threaded nmod_mat_muls. Thus mul_multi_modular will be threaded.

I don't know how you are going to find regressions. Have you tried benchmarking for matrices with dimensions in the thousands and bits in the many hundreds? It would take weeks to run the benchmarks in order to find any regressions.

This PR improves things out to dimension 1000 and bits 1000. Your example is simply too large to seriously optimise for without an application.

The objective here was to improve the algorithm selection in the presence of BLAS and your new fmpz_mul_blas out to a reasonable range, not to make the code perfect in all cases. It already took days to do this optimisation. That's days I really don't have to waste.

2021-03-25 11:17 UTC, fredrik-johansson commented
I'm a bit skeptical about unconditionally using fmpz_mat_mul_strassen for any matrix of size > 500.

2021-03-25 11:18 UTC, tthsqe12 commented
Ah, I am starting to understand this pr better :)
While jumping right into tuning fmpz_mat_mul will make it go faster today, it
leaves surprises in the individual methods for us to discover tomorrow.
My issues are with the `fmpz_mat_mul_multi_modular`, as this where I noticed
the regression.

The main this is this:

> If the dimension is large, mul_multi_modular will (presumably) have threaded nmod_mat_muls. Thus mul_multi_modular will be threaded.

to which I say: nmod_mat_mul's are not the only things done by mul_multi_modular.

If you would like, you can confirm my timings with the code as the end.

current trunk with ./configure --disable-static --with-blas
```
 mul: 10608 ms (1 threads)
 mul: 10221 ms (2 threads)
 mul: 8649 ms (3 threads)
 mul: 7767 ms (4 threads)
 mul: 7455 ms (5 threads)
 mul: 7014 ms (6 threads)
 mul: 6966 ms (7 threads)
 mul: 6633 ms (8 threads)
total: 65313
```


this pr:
```
 mul: 18857 ms (1 threads)
 mul: 18686 ms (2 threads)
 mul: 17975 ms (3 threads)
 mul: 18010 ms (4 threads)
 mul: 18286 ms (5 threads)
 mul: 17951 ms (6 threads)
 mul: 18278 ms (7 threads)
 mul: 17851 ms (8 threads)
total: 145894
```


profile code:

```
#include <stdio.h>
#include <stdlib.h>
#include <gmp.h>
#include "flint.h"
#include "fmpz.h"
#include "fmpz_vec.h"
#include "fmpz_mat.h"
#include "ulong_extras.h"
#include "profiler.h"

int main(void)
{
    slong i, j;
    FLINT_TEST_INIT(state);

    for (i = 0; i < 1; i++)
    {
        slong m, n, k;
        fmpz_mat_t A, B, C;
        flint_bitcnt_t bits = 4000;
        slong total;
        timeit_t timer;

        m = 500 + n_randint(state, 21);
        n = 500 + n_randint(state, 21);
        k = 500 + n_randint(state, 21);

        fmpz_mat_init(A, m, n);
        fmpz_mat_init(B, n, k);
        fmpz_mat_init(C, m, k);

        fmpz_mat_randtest(A, state, bits + 1);
        fmpz_mat_randtest(B, state, bits + 1);
        fmpz_mat_randtest(C, state, bits + 1);

        total = 0;
        for (j = 1; j <= 8; j++)
        {
            flint_set_num_threads(j);

            timeit_start(timer);
            fmpz_mat_mul_multi_mod(C, A, B);
            timeit_stop(timer);
            flint_printf(" mul: %wd ms (%wd threads)\n", timer->wall, j);
            total += timer->wall;
        }

        flint_printf("total: %wd\n", total);

        fmpz_mat_clear(A);
        fmpz_mat_clear(B);
        fmpz_mat_clear(C);
    }

    FLINT_TEST_CLEANUP(state);

    flint_printf("PASS\n");
    return 0;
}
```

2021-03-25 11:33 UTC, wbhart commented
@fredrik-johansson Why? Eventually Strassen has to win on ground of complexity.

If you want to prove your scepticism well-founded, run some timings yourself on a modern machine past where I did and see.

I think both of you are not understanding how much work was required to do this. We have six algorithms, with and without blas, with 1-8 threads, different dimensions and bit sizes. It's really impossible to get something that is going to be good everywhere.

2021-03-25 11:36 UTC, wbhart commented
And what is even the point if tomorrow more algorithms or improvements are going to be made.

The main point of this PR was to retune for 20 bit primes in fmpz_mat_mul_modular. When I was already a day or two into it, I was supplied with a new function to benchmark (fmpz_mat_mul_blas), which meant I had to throw a day's work away and start again.

If you guys want to work on this when I am done, be my guest. From my point of view this is currently pretty good on a machine with and without blas, with 1-8 threads in the region 1-1000 bits (input) and 1-1000 dimension, except for the inevitable small regions where the tuning is not perfect.

2021-03-25 11:41 UTC, fredrik-johansson commented
But multi_mod multiplication *also* has Strassen complexity. Indeed, assuming quadratic integer multiplication (the only case we're really concerned about here), fmpz_mat_mul_strassen costs O(b^2 n^2.8) while fmpz_mat_mul_multi_mod costs O(b n^2.8 + b^2 n^2), so it should be better asymptotically.

2021-03-25 12:47 UTC, wbhart commented
If you fix the size of b and take into account implied constants, the comparison is O(n^2.8) vs O(n^2.8).

If you don't fix the size of b then the cost of integer multiplication becomes relevant.

I'm not saying you are wrong, but it's not what I observed in the range I tuned for. Please feel free to do better. I don't have any more time to spend on this PR. Nobody has asked me to tune for problems in the ranges you are talking about.

2021-03-25 16:14 UTC, fredrik-johansson commented
The case where b = O(n) or b = O(n log n) is interesting, and where you get a complexity reduction. Of course this analysis is too simplistic because it ignores the relative costs of additions and so on, but it's a reasonable first-order approximation. E.g. here are results on my machine (no BLAS, one thread) for size n randbits matrices with proportional bits:

```
bits == n:

n =   579  old time = 4.543     new time = 5.291   (1.16x slower)
n =   810  old time = 15.47     new time = 16.772    (1.08x slower)
n =  1134  old time = 54.001    new time = 73.172    (1.36x slower)
n =  1587  old time = 182.916   new time = 247.545   (1.35x slower)

bits == 3*n:

n =   579  old time = 15.279     new time = 18.706   (1.22x slower)
n =   810  old time = 47.698     new time = 60.256    (1.26x slower)
n =  1134  old time = 184.749    new time = 278.989    (1.56x slower)
```

On the other hand:

* Strassen may have an advantage for structured matrices.
* Another aspect to consider is memory usage, which is going to be the real limiting factor when matrices get enormous. fmpz_mat_mul_strassen only needs two temporary (n/2)x(n/2) matrices, requiring 0.25x extra memory over just storing the input and output matrices (slightly more accounting for recursions). Multimodular multiplication meanwhile needs something like 1.5x extra memory, or 4.5x with BLAS (using only 20 bits per 64-bit word), though that is avoidable if we forgo asymptotically fast reduction/CRT.

2021-03-25 16:46 UTC, fredrik-johansson commented
Yes, seconds.

Though I'm actually seeing around 20% slowdown with Strassen for fixed bits == 100 as well.

2021-03-26 16:26 UTC, tthsqe12 commented
@wbhart If you merge this, I wouldn't mind working off of it for the next round of updates.

2021-03-26 23:14 UTC, wbhart commented
You can fetch from me and check out the branch. Then make your own branch based on it.

I won't merge it as Fredrik also has reservations about this tuning.

2021-03-27 07:58 UTC, fredrik-johansson commented
I just have a reservation about the new Strassen cutoff, which as far as I can tell leads to clear regressions.

As I said, it could still be useful to switch to Strassen for memory reasons, when dim * dim * bits > 4 GB, say.

2021-03-27 08:07 UTC, fredrik-johansson commented
By the way, something important we're not doing yet is to optimize for tall or skinny (rectangular) matrices, especially in mul_strassen.

This doesn't need to be horribly complicated; it should be enough to check if some dim is >= 2x the smallest dim (say), and then iterate over window matrices with roughly square blocks.

This is important for the Brent-Kung algorithm which builds matrices of size n^0.5 x n for composing length-n polynomials.

2021-03-27 17:20 UTC, fredrik-johansson commented
There's also FFT multiplication to consider. Unfortunately, the fft module doesn't have a simple interface for representing and doing arithmetic on integers in the transformed representation. I guess this could be achieved by wrapping fft_precache / fft_convolution_precache?

Though Schönhage-Strassen might not be ideal unless the numbers have millions of digits. This reminds me that I have a copy of David Harvey's 62-bit FFT. Is this something we might consider adapting instead of reinventing the wheel?

Let's not forget about fmpz_mat_sqr, by the way :-)

2021-03-29 09:08 UTC, wbhart commented
I guess we could add an interface for FFT representation. It's a bit complicated though as it depends on the size of all operands you are going to use. You may need a longer convolution length at some point in the calculation. It's hard to work with that.

We definitely need to implement a good small primes FFT (or use David's). The thing is, on modern PC's it might be hard to demonstrate a real performance gain in relevant regions. We really need to keep up with the technology, and this is quite a bit of work.

2021-03-29 09:21 UTC, fredrik-johansson commented
For matrix multiplication, I guess you would just compute an upper bound for all the outputs. Doing something clever for non-uniform matrices seems much more difficult.

Two reasons to consider matrices with huge coefficients, by the way: numerical computations with high precision (Arb sometimes uses fmpz_mat), and mul_KS for matrices over number fields (I use this in Calcium -- though polynomial interpolation might be better?).

2021-03-29 12:51 UTC, wbhart commented
I think it is best to open tickets for these ideas. This PR was not about doing everything possible to speed up matrix multiplication, but was very narrow in scope. I won't have time to work on this now.

2021-03-30 14:36 UTC, tthsqe12 requested changes

2021-03-30 15:02 UTC, wbhart commented on nmod_mat.h
>  #define NMOD_MAT_OPTIMAL_MODULUS_BITS (FLINT_BITS-5)
We'll just have to fix this. It's a precomputed inverse I think.

2021-04-12 13:55 UTC, tthsqe12 commented
@wbhart Since there are not very many code changes here, I hope you don't mind if I incorporate these changes into my tuning branch. I am going to make two sections in the code, one for with blas, and one for without blas. The code will be much more readable over the alternative of interspersing #if HAVE_BLAS everywhere inside everything.

2021-04-13 12:10 UTC, wbhart commented
Yep fine for me.

2021-04-13 12:32 UTC, fredrik-johansson commented
+1

2021-04-16 14:06 UTC, closed without merging